### ISSUE TITLE
proxy version shows "alpha"

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/proxy#112]
Unlike https://github.com/clearcontainers/shim/issues/62, this is a bug. `git describe`, which is used in the `Makefile` to identify the version only works on annotated tags. But the newest annotated tag is `3.0.0-alpha.3`, whereas the newest tag is in fact `3.0.0-beta.1`.

The makefile is confusing as it also defines a `VERSION := ...` variable. We should probably just remove that.

**Comment by egernst** [comment]
I went through and updated proxy tags as follows:
 git for-each-ref  --> indicated 3.0.0-beta.1 was a lightweight tag
git push --delete origin 3.0.0-beta.1
git tag -d 3.0.0-beta.1
 git tag -am "3.0.0-beta.1 release" 3.0.0-beta.1 817d71ef32
git push origin 3.0.0-beta.1

If you do a git fetch --tags you should see this is updated.

I noticed we didn't have a alpha.4 tag in the repo, so I added this as well.  This is presumably because nothing had changed since alpha.3.

@jodh-intel  can you verify and close?

**Comment by jodh-intel** [comment]
This does now work but I've noticed that the new tag you've pushed isn't signed but all the others are.

Any thoughts on this @jcvenegas, @sameo? I'd favour signing but if we agree on that approach, it should be added to https://github.com/clearcontainers/runtime/wiki/Release-Checklist atleast (which already specifies an annotated tag).

**Comment by egernst** [comment]
@jodh-intel -- I agree this makes sense.  It was inconsistent before, but that was because the non-signed were the lightweight!  Let me look @ updating this (for runtime, proxy and shim)

**Comment by egernst** [comment]
@jodh-intel  -- updated tags to include a gpg signature.
