### ISSUE TITLE
Reduce the runtime protocol

### ISSUE THREAD

**Issue by sameo** [clearcontainers/proxy#2]
In order to be less hyperstart specific, reduce the current runtime protocol to the following commands:

- `Hello`: For registering a new VM. This returns a token to be used by a shim to connect to the proxy through the shim protocol.
- `Bye`: For unregistering a VM.
- `Attach`: Attach to an already running VM. This returns a token for the shim.
- `Command`: Send a raw CTL command

**Comment by dlespiau** [comment]
@sameo The main goal is to remove allocateIO. However the runtime uses IO sequence numbers in the exec command (which is what allocateIO provides). I see 2 options:

1. The runtime decides of random numbers and rely on hyperstart rejecting the exec command if there's already a process with overlapping sequence numbers. Note that the proxy still needs to decode the hyperstart commands going on the wire because we need to associate sequence numbers to shims.
2. The runtime always uses 1, 2, 3 and the proxy rewrites those numbers (very much like address relocations), knowing what sequence number are safe (global state maintained by the proxy).

Given that the proxy needs to inspect the hyperstart commands in any case, option 2. seems like the natural choice.

**Comment by dlespiau** [comment]
@sameo To limit the amount of work before we close 2.1, I'd like to keep the Hyper proxy command. Otherwise I need to adapt both the 2.1 proxy and  the 2.1 runtime to receive and send raw hyperstart commands (and add that support to virtcontainers as well).

Pros for keeping Hyper:
- I don't think there's much value in raw data Vs the Hyper command
- The proxy needs to know which agent we are talking to (needs to inspect hyper command), so a generic raw command would need to be augmented by an agent type: runtime could tell the proxy about the agent with Hello/Attach or we could indicate the agent type in the flags field of the proxy packet header.
- We currently don't use 2 agents with this proxy, so we can wait until we do and decide what's best then (generic Command/raw data Vs a specific Agent() payload).
- The Hyper payload seems to work with the proxy interface in virtcontainers

Cons for keeping Hyper:
- There are binary commands in the hyperstart protocol (send and receive a file from the VM). We don't currently use them so the Hyper command (JSON only) is enough for now. There are ways around it if we do need the send receive hyper commands: implement the raw hyper interface then or encode the data in the JSON payload (say base64).

Give the above, I think it's reasonable to keep the Hyper payload and implement a protocol addition if/when we need it while still be compatible with 2.1.

**Comment by sameo** [comment]
> 2. The runtime always uses 1, 2, 3 and the proxy rewrites those numbers (very much like address relocations), knowing what sequence number are safe (global state maintained by the proxy).

That sounds like the right approach but I think it is racy: `Attach` will have the proxy allocate a set of IO seqnums, and associate a token with them. Then proxy receives a new `Hyper` command for `execcmd` and needs to associate it with a previously allocated set of IO seqnums. If proxy gets 2 `Attach` in a row, it won't be able to know which seqnums to associate with `execcmd`.

I think a derivative 3rd option would fix that:

3.  The runtime always uses 1, 2, 3 and the proxy rewrites those numbers (very much like address relocations), by associating a token with the right I/O sequence numbers. The `Hyper` command would take one additional `token` parameter.

**Comment by sameo** [comment]
@dlespiau 

> @sameo To limit the amount of work before we close 2.1

I don't think it would be reasonable to put the proxy and shim protocol changes as 2.1 blocker. We can keep 01org/cc-oci-runtime running the current shim/proxy protocols and tag a 2.1 release while we're working on the protocol changes on the clearcontainers repos. Once those are ready, we can push back the changes to 01org/cc-oci-runtime as a post 2.1 change. Sorry for the confusion.

> Give the above, I think it's reasonable to keep the Hyper payload and implement a protocol addition if/when we need it while still be compatible with 2.1.

I am fine with that, but I think we need to add a token field to the data header. See https://github.com/clearcontainers/proxy/issues/2#issuecomment-274780835.
Also, could we at least rename it for now ?

**Comment by dlespiau** [comment]
Sure, we can add the token to Hyper and we can also rename it to "Command". It's a bit awkward to have that generic name form a payload that would have been designed for hyperstart and may not fit other agents, but I'm sure we can deal with it when the time comes (worst case scenario, we can introduce a Command2)

**Comment by sameo** [comment]
@dlespiau fair enough, let's keep the `Hyper` name. Worst case we create a `Command` later on for a more generic case.

**Comment by dlespiau** [comment]
Initial implementation now merged!
