### ISSUE TITLE
proxy should not use magic numbers

### ISSUE THREAD

**Issue by sameo** [clearcontainers/proxy#6]
_From @jodh-intel on October 26, 2016 8:0_

The proxy code is sprinkled with magic numbers. These should be converted to well-documented consts.

See review comments on PR #306

_Copied from original issue: 01org/cc-oci-runtime#351_

**Comment by dlespiau** [comment]
For reference, the PR in the original bug is: https://github.com/01org/cc-oci-runtime/pull/306.

Since then, the code with the "magic numbers" has been moved to virtcontainers and constants like the ctl/io header sizes have been created.

There's still one magic size (a "maximum" size of the CTL paquets), but with a long comment to explain the why. On that note, our hyperstart code doesn't support large (>10k) CTL commands, which could backfire if the environment send with an exec command is very large. Will open a separate bug in virtcontainers for that.
